version: "3.9"

services:
  nginx-as-load-balancer:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - "1111:80"

  app1:
    build:
      context: .
      dockerfile: application.Dockerfile
      args:
        SERVER_NAME: server1
    container_name: app1

  app2:
    build:
      context: .
      dockerfile: application.Dockerfile
      args:
        SERVER_NAME: server2
    container_name: app2

  app3:
    build:
      context: .
      dockerfile: application.Dockerfile
      args:
        SERVER_NAME: server3
    container_name: app3    
